config/routes.rb
Buddyup::Application.routes.draw do
  root :to => "teams#index"
  resources :people, :except => [:edit, :update, :show]

  resources :teams, :except => [:edit, :update] do
    resources :team_assignments, :only => [:create, :destroy]
    member do
      get 'send_weekly_pairs' => 'teams#send_weekly_pairs'
      get 'show_weekly_pairs' => 'teams#show_weekly_pairs'
    end
  end

  get '/about' => 'application#about'
end

app/models/buddy_pair.rb
class BuddyPair < ActiveRecord::Base
  attr_accessible :permutation
  validates_presence_of :permutation, :team_id
  validate :check_data_type
  belongs_to :team
  has_many :people

  def self.clean_weekly_pair_records
    BuddyPair.all.each do |pair|
      pair.people.delete_all
    end
  end

private
  def check_data_type
    if self.permutation.class != Array
      errors.add(:permutation, "Buddy permutation must be an array")
    end
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name, :email, :team_names
  attr_writer :team_names

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, :presence => true
  validates :email, :presence => true,
                    :format => { :with => EMAIL_REGEX },
                    :uniqueness => true
  has_many :team_assignments, :dependent => :destroy
  has_many :teams, :through => :team_assignments
  belongs_to :buddy_pair
  before_save :downcase_email
  after_save :assign_teams

  #custom getter to return the current teams the person belongs to for edit actions if needed.
  def team_names
    @team_names ||= teams.map(&:name).join(',')
  end

private
  def assign_teams
    if @team_names
      teams = @team_names.split(',').map(&:strip).map do |name|
        Team.find_or_create_by_name(name)
      end
      self.teams = teams
      teams.each { |team| team.generate_pair_for_new_member(self) }
    end
  end

  def downcase_email
    email.downcase!
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name
  attr_accessor :member_email

  validates :name, :presence => true,
                   :length => { :maximum => 10 }

  has_many :team_assignments, :dependent => :destroy
  has_many :members, :source => :person, :through => :team_assignments
  has_many :buddy_pairs

  def member_email=(email)
    self.members = Person.find_by_name(email)
  end

  #throw into rake task
  def generate_pair_records
    generate_permutations.each do |pair|
      self.buddy_pairs.create(permutation: pair)
    end
  end

  def generate_pair_for_new_member(member)
    self.members.pluck(:id).each do |existing_member_id|
      next if member.id == existing_member_id
      pair = [member.id, existing_member_id].sort
      self.buddy_pairs.create(permutation: pair)
    end
  end

  #a lot going on in this method. would like to refactor this.
  #if using clockwork file, please remove #clean_weekly_pair_records!
  def generate_weekly_pairs
    clean_weekly_pair_records
    weekly_pairs = []
    self.buddy_pairs.shuffle.each do |pair_obj|
      pair_ids = pair_obj.permutation
      person1 = Person.find_by_id(pair_ids[0])
      person2 = Person.find_by_id(pair_ids[1])
      next if should_not_pair?(pair_obj, person1, person2)
      pair_obj.people.push(person1, person2)
      pair_obj.update_attribute(:has_been_assigned, true)
      weekly_pairs.push([person1, person2])
    end
    reset_pair_records if all_pairs_assigned?
    orphan_members.each do |member|
      member.count == 1 ? weekly_pairs.sample.concat(member) : weekly_pairs.push(member)
    end
    weekly_pairs
  end

  def destroy_related_pairs(member)
    #destroy_all or delete_all do not work here on the array
    self.buddy_pairs.select{|pair| pair.permutation.include?(member.id) }.each(&:delete)
  end

private
  def generate_permutations
    #pluck out all person_id for a given team and generate unique permutations
    self.members.pluck(:id).permutation(2).to_a.map(&:sort).uniq
  end

  def should_not_pair?(pair_obj, person1, person2)
    return true if pair_obj.has_been_assigned || person1.buddy_pair || person2.buddy_pair
    false
  end

  def all_pairs_assigned?
    return false if buddy_pairs.select{|pair| !pair.has_been_assigned}.any?
    true
  end

  def reset_pair_records
    buddy_pairs.update_all(:has_been_assigned => false)
  end

  def orphan_members
    orphans = members.where(:buddy_pair_id => nil).shuffle
    pairs = []
    while orphans.any?
      pairs.push orphans.pop(2)
    end
    pairs
  end

  def clean_weekly_pair_records
    buddy_pairs.each { |pair| pair.people.delete_all }
  end
end

app/models/team_assignment.rb
class TeamAssignment < ActiveRecord::Base
  attr_accessible :has_been_assigned
  belongs_to :person
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def about
    render 'layouts/about'
  end
private
  # allowing access to presenters in the controller
  def present(object, klass=nil)
    klass ||= "#{object.class}".constantize
    klass.new(object, view_context)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
    #beaming down all teams for auto-complete feature.
    @teams = Team.all
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      flash[:success] = "Person successfully created."
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    Person.destroy(params[:id])
    flash[:success] = 'Person successfully deleted.'
    redirect_to request.referer
  end
end

app/controllers/team_assignments_controller.rb
class TeamAssignmentsController < ApplicationController
  def create
    @team = Team.find_by_id(params[:team_id])
    @member = Person.find_by_email(params[:team][:member_email])
    if @member
      @team.members << @member
      @team.generate_pair_for_new_member(@member)
      flash[:success] = "Team member successfully added!"
      redirect_to team_path(@team)
    else
      flash[:warning] = "Person does not exist :("
      redirect_to request.referrer
    end
  end

  def destroy
    team = Team.find_by_id(params[:team_id])
    member = Person.find_by_id(params[:id])
    team.members.delete(member)
    team.destroy_related_pairs(member)
    flash[:success] = "Member successfully removed from the team."
    redirect_to request.referrer
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    if @team.save
      flash[:success] = "Team successfully created."
      redirect_to team_path(@team)
    else
      render :new
    end
  end

  def show
    @team = Team.find_by_id(params[:id])
    @team_members = @team.members
  end

  def destroy
    Team.destroy(params[:id])
    flash[:success] = "Team successfully deleted."
    redirect_to root_path
  end

  def send_weekly_pairs
    team = Team.find_by_id(params[:id])
    pairs = team.generate_weekly_pairs
    respond_to do |format|
      @pairs.each do |pair|
        pair.each do |person|
          buddies = pair - [person]
          TeamMemberPairMailer.delay.weekly_pair(person, buddies, team)
        end
      end
      format.html{ 200 }
    end
  end

  #debugging only. Can generate inifinite number of buddy pairs.
  def show_weekly_pairs
    BuddyPair.clean_weekly_pair_records
    @team = Team.find_by_id(params[:id])
    @pairs = @team.generate_weekly_pairs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #allows view templates to take in blocks and pass it on to presenter object
  def present(object, klass=nil)
    klass ||= "#{object.class}Presenter".constantize
    #self is the template object
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_flash_message.html.erb
<div class='row'>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      </button>
      <a class="brand" href="/">BuddyUp</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'New Team', new_team_path %></li>
          <li><%= link_to 'New Person', new_person_path %></li>
          <li><a href="/about">About</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
</nav>

app/views/layouts/about.html.erb
<script src="https://bitbucket.org/4thethrillofit/buddy-up/src/555c3bd8bc6a0903a077b4513a92098c7a35c408/README.rdoc?embed=t"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buddyup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script>
   PageContent = {};
  </script>
</head>
<body>
  <%= render :partial => 'layouts/header' %>
  <div class='main container'>
    <%= render :partial => 'layouts/flash_message' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/people/index.html.erb
<div class='row people'>
  <h3>Everyone</h3>
  <ul>
  <% PeoplePresenter.new(@people, self).person_presenters.each do |person| %>
    <li><%= person.name %>, <%= person.email %></li>
  <% end %>
  </ul>
</div>

app/views/people/new.html.erb
<h3>Create a new person</h3>
<div class='row new-person-form'>
<div class='span12'>
<%= form_for @person do |f| %>
  <%= render 'shared/error_messages', :target => @person %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.text_field :email, placeholder: 'Email' %>
  <div class='row team-box'>
  <%= f.text_field :team_names, type: 'hidden', class: "teams" %>
    <input type='text' class = "tags-input" id='team-tags' placeholder="Team Names" data-provide='typeahead' />
    <section class='suggestion-box'></section>
  </div>
  <%= f.submit "Submit", class: 'btn btn-warning' %>
<% end %>
</div>
</div>

<script type="text/javascript">
  PageContent.suggestions = <%= @teams.map(&:name).to_json.html_safe %>;
</script>

app/views/people/show.html.erb
<div class='row'>
  <% present @person do |person_presenter| %>
    <%= person_presenter.name %>
  <% end %>
  <% p = PersonPresenter.new(@person, self) %>
  <%= p.name %>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div class='error-messages'>
  <div class='alert alert-error'>
    <%= pluralize(target.errors.count, 'error') %> prevented this record from being saved.
    <ul>
    <% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>